/**
 * Super Admin API: User Creatives
 * GET /api/super-admin/users/[id]/creatives
 *
 * Returns recent creatives generated by a specific user
 */

import { NextRequest, NextResponse } from 'next/server'
import { superAdminGuard } from '@/lib/middleware/super-admin-guard'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  return superAdminGuard(request, async (req, { adminClient }) => {
    const { id: userId } = await params
    const supabase = adminClient

    try {
      const { searchParams } = new URL(req.url)
      const limit = parseInt(searchParams.get('limit') || '10')

      // Fetch recent creatives by this user
      const { data: creatives, error } = await supabase
        .from('creatives')
        .select('id, title, format_id, created_at, thumbnail_url')
        .eq('created_by', userId)
        .order('created_at', { ascending: false })
        .limit(limit)

      if (error) {
        console.error('[super-admin] Failed to fetch user creatives:', error)
        return NextResponse.json(
          { error: 'Failed to fetch creatives', details: error.message },
          { status: 500 }
        )
      }

      return NextResponse.json({
        success: true,
        creatives: creatives || [],
        total: creatives?.length || 0,
      })
    } catch (error) {
      console.error('[super-admin] Exception fetching user creatives:', error)
      return NextResponse.json(
        {
          error: 'Internal server error',
          details: error instanceof Error ? error.message : 'Unknown error',
        },
        { status: 500 }
      )
    }
  })
}
