export { Navbar } from './navbar'
export { HeroSection } from './hero-section'
export { FeaturesSection } from './features-section'
export { VerticalsSection } from './verticals-section'
export { HowItWorksSection } from './how-it-works-section'
export { PricingSection } from './pricing-section'
export { CTASection } from './cta-section'
export { Footer } from './footer'
